cache: bundler
language: ruby
install:
  - 'gem update --system'
  - 'gem --version'
  - 'gem install bundler -v 1.17.2'
  - 'bundle --version'
  - bundle
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
os:
  - linux
  - osx
notifications:
  email: false
